### PR TITLE
Separate estimation and correction logic

### PR DESCRIPTION
**Pull request by DarwinAwardWinner**
I wanted to use this beta adjustment method with estimated cell proportions from minfi, so I separated the estimation logic into a separate function and added an argument to `adjust.beta` to allow you to pass in pre-specified cell type proportions instead of have it estimate them.

Note that my changes are structured to preserve backward compatibility, which results in some weird design, such as the fact that passing cell type proportions to `adjust.beta` with `est.only=TRUE` is a no-op. Also, git kind of mangles the diff, since I'm effectively splitting a function in two.

### CODE REVIEW

**Comment by brentp** [comment]
excellent! do you mind adjusting the README? I think it should be just the last line.

**Comment by DarwinAwardWinner** [comment]
Sure, there's a few other issue I've spotted as well. I'll update you when I've fixed them.

**Comment by brentp** [comment]
since this is a git repo and the api surface area is so small, I'm not worried about backwards compat. but I'll trust your judgement as I'm not expecting to use this for a while.

**Comment by DarwinAwardWinner** [comment]
Ok, I've done some cleanup. I think this is ready to merge.

**Pull request merged**
